spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456  #数据库名、用户名和密码改为自己的
    driver-class-name: com.mysql.cj.jdbc.Driver

  server:
  port: 8761
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: czh123
#    keyAlias: tomcat
#    keyStoreType: PKCS12